# .streamlit/config.toml

[theme]
primaryColor="#1E88E5"
backgroundColor="#0E1117" # Example dark theme background
secondaryBackgroundColor="#262730" # Example dark theme secondary background
textColor="#FAFAFA"
font="sans serif" # Or "Inter" if you've configured it globally

# You can also specify specific font colors for different elements if needed
# For example:
# [theme.textColor]
# primary = "#FFFFFF"
# secondary = "#D3D3D3"
# success = "#28A745"
# info = "#17A2B8"
# warning = "#FFC107"
# error = "#DC3545"

[logger]
level = "INFO" # Set to "DEBUG" for more verbose logging from Streamlit itself

[runner]
# If you have issues with file watching or caching, you might adjust these,
# but defaults are usually fine.
# fastReruns = true
# enforceSerializableSessionState = true

[server]
# port = 8501 # Default
# headless = true # Useful for some CI/CD environments
# enableCORS = false # Default
# enableXsrfProtection = true # Default
