# .streamlit/config.toml

[theme]
# Sets the base theme to dark mode
base="dark"

# Primary color for interactive elements
primaryColor="#7792E3" # A pleasant blue, good for dark themes

# Background colors
backgroundColor="#0E1117" # Standard Streamlit dark background
secondaryBackgroundColor="#1C1E26" # Background for elements like sidebar, cards (if not overridden by CSS)

# Text color
textColor="#FAFAFA" # White or very light gray for general text

# Font
font="Inter" # Matches the font imported in style.css. Use "sans serif" as a fallback if Inter causes issues.

[logger]
# Sets the default log level for Streamlit's internal logger
level = "INFO" # Options: "error", "warning", "info", "debug"

[runner]
# Allows Streamlit to run Python scripts with "magic" commands (e.g., rendering DataFrames directly)
magicEnabled = true

[server]
# headless = true # Uncomment if running in a headless environment
# port = 8501 # Default port
