# .streamlit/config.toml

[theme]
base="dark"
primaryColor="#7792E3" # A pleasant blue, good for primary actions
backgroundColor="#0E1117" # Standard dark background
secondaryBackgroundColor="#262730" # Slightly lighter for cards, sidebars etc.
textColor="#FAFAFA" # Off-white for good readability on dark backgrounds
font="sans serif" # Or "serif", "monospace"

# You can also specify specific font colors for different elements if needed
# For example:
# [theme.textColor]
# primary = "#FFFFFF"
# secondary = "#D3D3D3"
# success = "#28A745"
# info = "#17A2B8"
# warning = "#FFC107"
# error = "#DC3545"

[logger]
level = "INFO" # Set to "DEBUG" for more verbose logging from Streamlit itself

[runner]
# If you have issues with file watching or caching, you might adjust these,
# but defaults are usually fine.
# fastReruns = true
# enforceSerializableSessionState = true

[server]
# port = 8501 # Default
# headless = true # Useful for some CI/CD environments
# enableCORS = false # Default
# enableXsrfProtection = true # Default
